config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from tutor.post.views import home_posts_view

urlpatterns = [
    path(
        "",
        home_posts_view,
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("tutor.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # app's urls
    path("post/", include("tutor.post.urls", namespace="post")),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tutor/post/urls.py
from django.urls import path

from .views import post_create_view
from .views import post_delete_view
from .views import post_details_view
from .views import post_tag_view
from .views import post_update_view

app_name = "post"
urlpatterns = [
    path("create/", view=post_create_view, name="create"),
    path("<pk>/", view=post_details_view, name="details"),
    path("edit/<pk>/", view=post_update_view, name="edit"),
    path("delete/<pk>/", view=post_delete_view, name="delete"),
]

# tags
tags_url = [
    path("tag/<str:slug>/", view=post_tag_view, name="tag"),
]

urlpatterns += tags_url

tutor/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="profile"),
]

tutor/post/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from utils.model import TimeStampModel

User = get_user_model()


class Post(TimeStampModel):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    title = models.CharField(max_length=50)
    body = models.TextField()
    image_url = models.URLField()

    author = models.ForeignKey(User, related_name="posts", on_delete=models.Case)
    tags = models.ManyToManyField("Tag")

    def __str__(self) -> str:
        return self.title


class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)

    def __str__(self):
        return self.name

tutor/users/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from utils.model import TimeStampModel


class User(AbstractUser):
    """
    Default custom user model for Tutor.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore[assignment]
    last_name = None  # type: ignore[assignment]

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:profile", kwargs={"username": self.username})


class Profile(TimeStampModel):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    image = models.ImageField(upload_to="avatar/", blank=True, null=True)
    bio = models.CharField(max_length=300, blank=True)

    def __str__(self) -> str:
        return self.user.username

tutor/post/forms.py
from django import forms
from django.forms import ModelForm

from .models import Post


class PostCreateForm(ModelForm):
    class Meta:
        model = Post
        fields = ["title", "body", "image_url", "tags"]
        labels = {"body": "Caption", "tags": "Categories"}

        widgets = {
            "body": forms.Textarea(
                attrs={
                    "rows": 3,
                    "placeholder": "add caption",
                    "class": "font1 text-4xl",
                },
            ),
            "tags": forms.CheckboxSelectMultiple(),
        }


class PostUpdateForm(ModelForm):
    class Meta:
        model = Post
        fields = ["title", "body", "image_url"]
        labels = {"body": "Caption", "tags": "Categories"}

        widgets = {
            "body": forms.Textarea(
                attrs={
                    "rows": 3,
                    "placeholder": "add caption",
                    "class": "font1 text-4xl",
                },
            ),
            "tags": forms.CheckboxSelectMultiple(),
        }

tutor/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.utils.translation import gettext_lazy as _

from .models import User


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):  # type: ignore[name-defined]
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):  # type: ignore[name-defined]
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

tutor/post/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from .forms import PostCreateForm
from .forms import PostUpdateForm
from .models import Post
from .models import Tag

# Create your views here.


def home_posts_view(request):
    posts = Post.objects.all()
    tags = Tag.objects.all()
    return render(request, "pages/home.html", {"posts": posts, "tags": tags})


class PostDetailsView(DetailView):
    template_name = "post/page_post.html"
    model = Post


post_details_view = PostDetailsView.as_view()


class PostCreateView(LoginRequiredMixin, CreateView):
    template_name = "post/create_post.html"
    form_class = PostCreateForm
    login_url = reverse_lazy("account_login")
    success_url = reverse_lazy("home")
    context_object_name = "post"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


post_create_view = PostCreateView.as_view()


class PostDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "post/delete_post.html"
    success_url = reverse_lazy("home")
    model = Post

    def form_valid(self, form):
        messages.success(self.request, "post deleted successfuly!")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Post did not delete successfully!")
        return super().form_invalid(form)


post_delete_view = PostDeleteView.as_view()


class PostUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "post/update_post.html"
    form_class = PostUpdateForm
    model = Post

    success_url = reverse_lazy("home")

    def form_valid(self, form):
        messages.success(self.request, "post updated successfuly!")
        return super().form_valid(form)


post_update_view = PostUpdateView.as_view()


class PostTagView(ListView):
    model = Post
    template_name = "pages/home.html"
    context_object_name = "posts"

    def get_queryset(self):
        slug = self.kwargs.get("slug")
        return Post.objects.filter(tags__slug=slug)


post_tag_view = PostTagView.as_view()

tutor/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from tutor.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    context_object_name = "user"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self) -> str:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user.get_absolute_url()

    def get_object(self, queryset: QuerySet | None = None) -> User:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self) -> str:
        return reverse("users:profile", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

tutor/templates/post/create_post.html
<h1 class="text-white">Create Post</h1>
<div class="card !p-8">
  <div class="flex items-center mb-6">
    <img class="h-5 object-cover mr-1" src="https://img.icons8.com/small/96/333333/search--v1.png" />
    <a href="https://www.flickr.com/explore" target="_blank" class="hover:underline text-gray-500">Find an image on Flickr</a>
  </div>

  <form hx-post="{% url 'post:create' %}" hx-trigger="submit delay:500ms" hx-swap="afterbegin show:top" hx-target="#all-posts">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="mt-1">Submit Post</button>
    <button onclick="closePopup()" class="button secondaryAction ml-1">Cancel</button>
  </form>
</div>

tutor/templates/post/delete_post.html
<h1>Delete Post</h1>
<div class="card !p-8">
  <div class="flex items-center mb-6">
    <p>Are you sure you want to delete this post?</p>
  </div>

  <form hx-post="{% url 'post:delete' post.uuid %}" hx-target="body" hx-trigger="submit delay:500ms" hx-swap="innerHTML">
    {% csrf_token %}
    <button type="submit" class="mt-1">Confirm</button>
    <a onclick="closePopup()" class="button secondaryAction ml-1">Go Back</a>
  </form>
</div>

tutor/templates/post/page_post.html
<article class="card">
    <div class="flex items-center justify-between px-4 h-14">
        <h3 class="text-lg font-bold w-[50%] truncate">Little Jedi</h3>
        <div class="text-sm text-gray-500">flickr @ <a href="" class="hover:underline" target="blank">John Doe</a></div>
    </div>
    <figure>
        <a href=""><img class="w-full" src="{{post.image_url}}"></a>
    </figure>
    <div class="p-4 pb-2">
        <a class="flex items-center gap-1 mb-4" href="">
            <img class="w-8 h-8 object-cover rounded-full" src="https://img.icons8.com/small/96/A9A9A9/happy.png">
            <span class="font-bold hover:underline">Lisa</span>
        </a>
        <p class="text-5xl mb-10 px-4 font1">{{post.title}}</p>
        <div class="flex items-center gap-2 text-sm mb-5">
            <a class="bg-gray-200 rounded-full px-3 py-1 hover:bg-gray-500 hover:text-white" href="">Animals</a>
            <a class="bg-gray-200 rounded-full px-3 py-1 hover:bg-gray-500 hover:text-white" href="">Cute</a>
        </div>
        <div class="flex items-center justify-between text-sm px-2">
            <a class="font-bold hover:underline" href="">
                Comments
                <span class="font-light text-gray-500 ml-2">3</span>
            </a>
            <div class="flex items-center gap-4 [&>a:hover]:underline">
                <div class="flex items-center gap-1">
                    <img class="w-5 -mt-1" src="https://img.icons8.com/small/24/000000/fire-heart.png">
                    1
                </div>
                <a href="">Like</a>
                <a href="">Edit</a>
                <a href="">Delete</a>
            </div>
        </div>
    </div>
</article>

<div class="card !pb-0 -mt-3">
    <form method="POST" class="flex items-center p-4" autocomplete="off">
        <input type="text" name="comment" placeholder="Add comment ..." maxlength="150">
        <button @click="open = false" class="block ml-2" type="submit">Submit</button>
    </form>
</div>

<div class="mb-20">
    <div id="tabs" class="ml-4 flex gap-1 mb-4">
        <a class="tab selected">Newest First</a>
        <a class="tab">Top Comments</a>
    </div>

    <div id="tab-contents">

        <comment class="card p-4 !mb-4">
            <div class="flex justify-between items-center">
                <a class="flex items-center gap-1 mb-2" href="">
                    <img class="w-8 h-8 object-cover rounded-full" src="https://img.icons8.com/small/96/A9A9A9/happy.png">
                    <span class="font-bold hover:underline">Bart</span>
                    <span class="text-sm font-normal text-gray-400">@bartsimpson</span>
                </a>
            </div>
            <p class="text-xl px-2">
                This is a comment from Bart
            </p>
            <div x-data="{ repliesOpen: false }" class="flex items-center justify-between flex-wrap text-sm px-2">
                <a @click="repliesOpen = !repliesOpen" class="font-bold hover:underline cursor-pointer">
                    <div class="inline-block" x-bind:class="repliesOpen && 'rotate-90 duration-300'">
                        <svg transform ="rotate(90)" width="9" height="9" viewBox="0 0 25 25">
                            <path d="M24 22h-24l12-20z"/>
                        </svg>
                    </div>
                    Replies
                    <span class="font-light text-gray-500 ml-1">1</span>
                </a>
                <div class="flex items-center gap-4 [&>a:hover]:underline">
                    <div class="flex items-center gap-1">
                        <img class="w-5 -mt-1" src="https://img.icons8.com/small/24/000000/fire-heart.png">
                        1
                    </div>
                    <a href="">Like</a>
                    <a href="">Delete</a>
                </div>

                <div x-show="repliesOpen" x-cloak class="basis-full mt-3 pl-8 grid grid-cols-1">

                    <reply class="flex items-end justify-between py-4 border-t">
                        <div class="flex">
                            <a href="">
                                <img class="w-8 h-8 object-cover rounded-full mr-2" src="https://img.icons8.com/small/96/A9A9A9/happy.png">
                            </a>
                            <div class="w-fit">
                                <a class="block" href="">
                                    <span class="font-bold hover:underline">Homer</span>
                                    <span class="text-sm text-gray-400">@homersimpson</span>
                                </a>
                                <div class="mr-3">This is a reply from Homer</div>
                            </div>
                        </div>
                        <div class="flex items-center gap-4 [&>a:hover]:underline">
                            <div class="flex items-center gap-1">
                                <img class="w-5 -mt-1" src="https://img.icons8.com/small/24/000000/fire-heart.png">
                                1
                            </div>
                            <a href="">Like</a>
                            <a href="">Delete</a>
                        </div>
                    </reply>

                    <form method="POST" class="replyform flex justify-between" autocomplete="off">
                        <input type="text" name="reply" placeholder="Add reply ..." maxlength="150">
                        <button class="block" type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </comment>

    </div>
</div>

tutor/templates/post/post.html
<main class="col-span-full md:col-span-2 md:mr-[5%] lg:mx-[10%] order-2 md:order-1">
  <article class="card">
    <div class="flex items-center justify-between px-4 h-14">
      <a class="flex items-center gap-1 mb-4" href="">
        <img class="w-8 h-8 object-cover rounded-full" src="{{ post.author.profile.image.url }}" />
        <a href="{% url 'users:profile' post.author.username %}" class="hover:underline ml-1">{{ post.author.username }}</a>
      </a>
      <h3 class="text-start leading-5 mr-1">{{ post.title }}</h3>
      <div class="text-sm text-gray-400 truncate"></div>
    </div>
    <figure>
      <a hx-get="{% url 'post:details' post.uuid %}" hx-trigger="click" hx-swap="innerHTML" hx-target="#popup"><img class="w-full" src="{{ post.image_url }}" /></a>
    </figure>
    <div class="p-4 pb-2">
      <p class="text-5xl mb-10 px-4 font1">{{ post.body }}</p>
      <div class="flex items-center gap-2 text-sm mb-5 flex-wrap">
        {% for tag in post.tags.all %}
          <a href="{% url 'post:tag' tag.slug %}" class="bg-gray-200 rounded-full px-3 py-1 hover:bg-gray-800 hover:text-white">{{ tag }}</a>
        {% endfor %}
      </div>
      <div class="flex items-center justify-between text-sm px-2">
        <a class="font-bold hover:underline" href="">
          Comments
          <span class="font-light text-gray-500 ml-1">3</span>
        </a>
        <div class="flex items-center gap-4 [&>a:hover]:underline">
          <div class="flex items-center gap-1">
            <img class="w-5 -mt-1" src="https://img.icons8.com/small/24/000000/fire-heart.png" />
            1
          </div>
          <a href="">Like</a>
          <a hx-get="{% url 'post:edit' post.uuid %}" hx-trigger="click" hx-swap="innerHTML" hx-target="#popup">Edit</a>
          <a hx-get="{% url 'post:delete' post.uuid %}" hx-trigger="click" hx-swap="innerHTML" hx-target="#popup">Delete</a>
        </div>
      </div>
    </div>
  </article>
</main>

tutor/templates/post/update_post.html
<h1>Edit Post</h1>
<div class="card p-4">
  <div class="flex items-center mb-4">
    <img class="w-20 h-20 object-cover rounded-xl mr-4" src="{{ post.image_url }}" />
    <h3 class="text-lg font-bold">{{ post.title }}</h3>
  </div>

  <div class="pb-2">
    <form hx-post="{% url 'post:edit' post.uuid %}" hx-target="body" hx-trigger="submit delay:500ms" hx-swap="innerHTML">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="pt-4">
        <button type="submit">Submit</button>
        <a onclick="closePopup()" class="button secondaryAction ml-1">Go Back</a>
      </div>
    </form>
  </div>
</div>