config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from tutor.post.views import home_posts_view

urlpatterns = [
    path(
        "",
        home_posts_view,
        name="home",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("tutor.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # app's urls
    path("post/", include("tutor.post.urls", namespace="post")),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tutor/post/urls.py
from django.urls import path

from .views import post_create_view
from .views import post_delete_view
from .views import post_details_view
from .views import post_tag_view
from .views import post_update_view

app_name = "post"
urlpatterns = [
    path("create/", view=post_create_view, name="create"),
    path("<pk>/", view=post_details_view, name="details"),
    path("edit/<pk>/", view=post_update_view, name="edit"),
    path("delete/<pk>/", view=post_delete_view, name="delete"),
]

# tags
tags_url = [
    path("tag/<str:slug>/", view=post_tag_view, name="tag"),
]

urlpatterns += tags_url

tutor/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="profile"),
]

tutor/post/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from utils.model import TimeStampModel

User = get_user_model()


class Post(TimeStampModel):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    title = models.CharField(max_length=50)
    body = models.TextField()
    image_url = models.URLField()

    author = models.ForeignKey(User, related_name="posts", on_delete=models.Case)
    tags = models.ManyToManyField("Tag")

    def __str__(self) -> str:
        return self.title


class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)

    def __str__(self):
        return self.name

tutor/users/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from utils.model import TimeStampModel


class User(AbstractUser):
    """
    Default custom user model for Tutor.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore[assignment]
    last_name = None  # type: ignore[assignment]

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:profile", kwargs={"username": self.username})


class Profile(TimeStampModel):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    image = models.ImageField(upload_to="avatar/", blank=True, null=True)
    bio = models.CharField(max_length=300, blank=True)

    def __str__(self) -> str:
        return self.user.username

tutor/post/forms.py
from django import forms
from django.forms import ModelForm

from .models import Post


class PostCreateForm(ModelForm):
    class Meta:
        model = Post
        fields = ["title", "body", "image_url", "tags"]
        labels = {"body": "Caption", "tags": "Categories"}

        widgets = {
            "body": forms.Textarea(
                attrs={
                    "rows": 3,
                    "placeholder": "add caption",
                    "class": "font1 text-4xl",
                },
            ),
            "tags": forms.CheckboxSelectMultiple(),
        }


class PostUpdateForm(ModelForm):
    class Meta:
        model = Post
        fields = ["title", "body", "image_url"]
        labels = {"body": "Caption", "tags": "Categories"}

        widgets = {
            "body": forms.Textarea(
                attrs={
                    "rows": 3,
                    "placeholder": "add caption",
                    "class": "font1 text-4xl",
                },
            ),
            "tags": forms.CheckboxSelectMultiple(),
        }

tutor/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.utils.translation import gettext_lazy as _

from .models import User


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):  # type: ignore[name-defined]
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):  # type: ignore[name-defined]
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

tutor/post/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from .forms import PostCreateForm
from .forms import PostUpdateForm
from .models import Post
from .models import Tag

# Create your views here.


def home_posts_view(request):
    posts = Post.objects.all()
    tags = Tag.objects.all()
    return render(request, "pages/home.html", {"posts": posts, "tags": tags})


class PostDetailsView(DetailView):
    template_name = "post/page_post.html"
    model = Post


post_details_view = PostDetailsView.as_view()


class PostCreateView(LoginRequiredMixin, CreateView):
    template_name = "post/create_post.html"
    form_class = PostCreateForm
    login_url = reverse_lazy("account_login")
    success_url = reverse_lazy("home")
    context_object_name = "post"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


post_create_view = PostCreateView.as_view()


class PostDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "post/delete_post.html"
    success_url = reverse_lazy("home")
    model = Post

    def form_valid(self, form):
        messages.success(self.request, "post deleted successfuly!")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Post did not delete successfully!")
        return super().form_invalid(form)


post_delete_view = PostDeleteView.as_view()


class PostUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "post/update_post.html"
    form_class = PostUpdateForm
    model = Post

    success_url = reverse_lazy("home")

    def form_valid(self, form):
        messages.success(self.request, "post updated successfuly!")
        return super().form_valid(form)


post_update_view = PostUpdateView.as_view()


class PostTagView(ListView):
    model = Post
    template_name = "pages/home.html"
    context_object_name = "posts"

    def get_queryset(self):
        slug = self.kwargs.get("slug")
        return Post.objects.filter(tags__slug=slug)


post_tag_view = PostTagView.as_view()

tutor/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from tutor.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    context_object_name = "user"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self) -> str:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user.get_absolute_url()

    def get_object(self, queryset: QuerySet | None = None) -> User:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self) -> str:
        return reverse("users:profile", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

tutor/templates/fragment/common/header.html
<header x-data="{ mobilenavOpen: false }" class="md:flex items-center justify-between [&>*]:px-8 bg-gray-800 h-20 text-white sticky top-0 z-40">
    <div class="flex items-center justify-between h-20">
        <logo>
            <a class="flex items-center gap-1" href="/">
                <img class="w-7 -mt-1" src="https://img.icons8.com/small/64/ffffff/fire-heart.png"/>
                <span class="text-lg font-bold">Awesome</span>
            </a>
        </logo>
        <mobileicon class="md:hidden">
            <a @click="mobilenavOpen = !mobilenavOpen" class="h-12 w-12 flex items-center justify-center cursor-pointer hover:bg-gray-700 rounded-lg">
                <img x-show="!mobilenavOpen" class="w-6 h-6 select-none" src="https://img.icons8.com/small/64/ffffff/menu.png"/>
                <img x-show="mobilenavOpen" x-cloak class="w-6 h-6 select-none" src="https://img.icons8.com/small/64/ffffff/delete-sign.png"/>
            </a>
        </mobileicon>
    </div>
    <nav x-show="mobilenavOpen" x-cloak class="md:!block bg-gray-800 h-screen w-screen md:h-auto md:w-auto -mt-20 md:mt-0 absolute md:relative z-[-1]"
        x-transition:enter="duration-300 ease-out"
        x-transition:enter-start="opacity-0 -translate-y-96"
        x-transition:enter-end="opacity-100 translate-y-0">
        <ul class="flex items-center navitems flex-col md:flex-row gap-8 md:gap-0 justify-center h-full -translate-y-10 md:translate-y-0">
            {% if user.is_authenticated %}

            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a hx-get="{% url "post:create" %}" hx-trigger="click" hx-swap="innerHTML" hx-target="#popup">Create Post</a></li>
            <li x-data="{ dropdownOpen: false }" class="relative">
                <a @click="dropdownOpen = !dropdownOpen" @click.away="dropdownOpen = false" class="cursor-pointer select-none">
                    <img class="h-8 w-8 rounded-full object-cover" src="{{user.profile.image.url}}"/>
                    {{user.username}}
                    <img x-bind:class="dropdownOpen && 'rotate-180 duration-300'" class="w-4" src="{{user.profile.image.url}}"/>
                </a>
                <div x-show="dropdownOpen" x-cloak class="absolute right-0 bg-white text-black shadow rounded-lg w-40 p-2 z-20"
                x-transition:enter="duration-300 ease-out"
                x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
                x-transition:enter-end="opacity-100 translate-y-0 scale-100">
                    <ul class="hoverlist [&>li>a]:justify-end">
                            <li><a hx-get="{% url 'users:profile' user.username %}" hx-target="body" hx-push-url="true" hx-trigger="click" hx-swap="innerHTML">My Profile</a></li>
                            <li><a href="{% url 'users:update' %}">Edit Profile</a></li>
                            <li><a href="{% url 'account_logout' %}">Log Out</a></li>
                            {% else %}

                            <li><a  href="{% url 'account_login' %}">Log In</a></li>
                            <li><a  href="{% url 'account_signup' %}">Sign Up</a></li>
                        {% endif %}
                    </ul>
                </div>
            </li>
        </ul>
    </nav>
</header>

tutor/templates/fragment/common/hero.html
<hero class="grid bg-gray-700 text-white text-center bg-cover z-10 relative bg-[url('https://live.staticflickr.com/65535/49909538937_3255dcf9e7_b.jpg')]">
  <div class="col-start-1 row-start-1 bg-gray-800 bg-opacity-40 w-full h-full"></div>
  <div class="col-start-1 row-start-1 py-24 px-10">
    <h1 class="font1 text-6xl title-fadein">Awesome Photos & Captions</h1>
    <p class="text-lg font-bold mb-5">Share your favorite Photos from Flickr and add a great caption</p>
    <a class="button" href="">Get Started</a>
  </div>
</hero>

tutor/templates/fragment/common/sidebar.html
<aside x-show="mobileSidebarOpen" x-cloak class="md:!block col-span-full md:col-span-1 lg:mr-[20%] order-1 md:order-2" x-transition:enter="duration-300 ease-out" x-transition:enter-start="opacity-0 -mt-96" x-transition:enter-end="opacity-100 mt-0">
  <section class="card p-4">
    <h2>Categories</h2>
    <h2>tags</h2>
    <ul class="hoverlist">
      {% for tag in tags %}
        <li class="highlight">
          <a href="{% url 'post:tag' tag.slug %}">
            <img class="w-8 h-8 object-cover mr-2" src="https://img.icons8.com/small/96/null/landscape.png" />
            <span class="font-bold text-sm">{{ tag.name }}</span>
          </a>
        </li>
      {% endfor %}
    </ul>
  </section>
  <section class="card p-4">
    <div class="flex items-center">
      <img class="w-7 mr-2 -mt-3" src="https://img.icons8.com/ios-glyphs/90/null/fire-heart.png" />
      <h2>Top Posts</h2>
    </div>
    <ul class="hoverlist">
      <li>
        <a href="" class="flex items-stretch justify-between">
          <div class="flex items-center truncate">
            <img class="w-10 h-10 rounded-lg object-cover mr-3 shrink-0" src="https://live.staticflickr.com/65535/50618365686_36f887ab88_c.jpg" />
            <img class="w-6 h-6 rounded-full object-cover mr-1" src="https://img.icons8.com/small/96/A9A9A9/happy.png" />
            <span class="font-bold text-sm mr-1">Homer</span>
          </div>
          <span class="text-sm font-light text-grey-500 shrink-0">3 Likes / 1</span>
        </a>
      </li>
      <li>
        <a href="" class="flex items-stretch justify-between">
          <div class="flex items-center truncate">
            <img class="w-10 h-10 rounded-lg object-cover mr-3" src="https://live.staticflickr.com/65535/50618365686_36f887ab88_c.jpg" />
            <img class="w-6 h-6 rounded-full object-cover mr-1" src="https://img.icons8.com/small/96/A9A9A9/happy.png" />
            <span class="font-bold text-sm mr-1">Homer</span>
          </div>
          <span class="text-sm font-light text-grey-500 shrink-0">3 Likes / 1</span>
        </a>
      </li>
    </ul>
  </section>
  <section class="card p-4">
    <div class="flex items-center">
      <img class="w-7 mr-2 -mt-3" src="https://img.icons8.com/ios-glyphs/90/null/fire-heart.png" />
      <h2>Top Comments</h2>
    </div>
    <ul class="hoverlist">
      <li>
        <a href="" class="flex items-stretch justify-between">
          <div class="flex items-center truncate">
            <img class="w-6 h-6 rounded-full object-cover mr-1" src="https://img.icons8.com/small/96/A9A9A9/happy.png" />
            <span class="font-bold text-sm mr-1 truncate">Homer : Comment</span>
          </div>
          <span class="text-sm font-light text-grey-500 shrink-0">3 Likes / 1</span>
        </a>
      </li>
      <li>
        <a href="" class="flex items-stretch justify-between">
          <div class="flex items-center truncate">
            <img class="w-6 h-6 rounded-full object-cover mr-1" src="https://img.icons8.com/small/96/A9A9A9/happy.png" />
            <span class="font-bold text-sm mr-1 truncate">Homer : Comment</span>
          </div>
          <span class="text-sm font-light text-grey-500 shrink-0">3 Likes / 1</span>
        </a>
      </li>
    </ul>
  </section>
</aside>